### ISSUE TITLE
オブジェクトエクスプローラから拡張編集ウィンドウに動画ファイルをドラッグアンドドロップした直後に出力しようとするとエラーになる

### ISSUE THREAD

**Issue by hebiiro** [rigaya/x264guiEx#3]
うちのオブジェクトエクスプローラから拡張編集ウィンドウに動画ファイルをドラッグアンドドロップした直後に出力しようとするとエラーになります。
![オブジェクトエクスプローラで出力エラー](https://user-images.githubusercontent.com/96464759/220871810-5f312a62-1c12-4d56-bf11-d1009955c574.png)
オブジェクトエクスプローラから DnD すると特殊なハンドルが生成されるようで、auo_encode.cpp の 1954 行あたりで、変数 size が無効な値になるようです。size を使う前に初期値を代入する、size が無効にならないように最初からバッファを渡しておく、というようにして回避してもらえないでしょうか。
```C++
#if 1
                    // handleの種類を確認する
                    std::vector<char> otibuffer(size = sizeof(PUBLIC_OBJECT_TYPE_INFORMATION), 0);
                    status = fNtQueryObject(handle.get(), ObjectTypeInformation, otibuffer.data(), otibuffer.size(), &size);
                    otibuffer.resize(size);
                    status = fNtQueryObject(handle.get(), ObjectTypeInformation, otibuffer.data(), otibuffer.size(), &size);
                    const auto oti = (PPUBLIC_OBJECT_TYPE_INFORMATION)otibuffer.data();
#else
                    // handleの種類を確認する
                    status = fNtQueryObject(handle.get(), ObjectTypeInformation, NULL, 0, &size);
                    std::vector<char> otibuffer(size, 0);
                    status = fNtQueryObject(handle.get(), ObjectTypeInformation, otibuffer.data(), otibuffer.size(), &size);
                    const auto oti = (PPUBLIC_OBJECT_TYPE_INFORMATION)otibuffer.data();
#endif
```
ちなみに、オブジェクトエクスプローラから DnD したあと一旦 AviUtl を再起動すれば特殊なハンドルは消滅するようで、正常に出力できるようになります。逆に再起動しなかった場合は DnD で追加した動画アイテムと音声アイテムを削除しても出力に失敗します。
環境は Win10 AviUtl1.10 拡張編集0.92 patch.aul r42 L-SMASH-Works_rev1103_Mr-Ojii_Mr-Ojii_AviUtl x264guiEx_3.16 です。

**Comment by hebiiro** [comment]
もしくは最初の fNtQueryObject の呼び出しのあとに
```
if (status != STATUS_INFO_LENGTH_MISMATCH) continue;
```
を追加するだけでもいいかもしれません。

**Comment by rigaya** [comment]
ご指摘のイレギュラーなハンドルが生じたときの対応策について、[x264guiEx 3.17](https://github.com/rigaya/x264guiEx/releases/tag/3.17)で対応いたしました。

教えていただいた ```STATUS_INFO_LENGTH_MISMATCH``` が返るかどうかのチェックを行うようにしています。

**Comment by hebiiro** [comment]
ありがとうございました！

**Comment by rigaya** [comment]
こちらこそありがとうございました。

x265guiEx/svtAV1guiEx/VVenCguiEx/ffmpegOut/QSVEnc/VCEEnc/NVEncにも少しずつ展開していきたいと思います。
