### ISSUE TITLE
10bitエンコードでおかしな挙動が起きる

### ISSUE THREAD

**Issue by resistorsytrus** [rigaya/x264guiEx#5]
x264guiExで出力->highbit depthをonにすると、異常な速さとビットレートでエンコされ、おかしな出力がされる

**Comment by resistorsytrus** [comment]
ffmpeg出力、x265guiexでも同様に10bitエンコがおかしくなる(AVI出力では正常)

**Comment by rigaya** [comment]
まずはx264guiExで確認いたしましたが、特に問題は再現致しませんでした。

10bitエンコがおかしいとは具体的になにがどのようにおかしいのでしょうか?

また、問題発生時のログをすべてご提示ください。

**Comment by resistorsytrus** [comment]
以下ログです(何故かビットレートが10kbpsを切っています)
------------------------------------------------------------------------------------------------------------------------------
[C:\Users\yyuuk\YobanashiDeceive.264]
------------------------------------------------------------------------------------------------------------------------------
auo [info]: x264guiEx 3.24 / Windows 11 x64 (22621) / Intel Pentium(R) Silver J5005 @ 1.50GHz [TB: 2.69GHz] (4C/4T)
auo [info]: video: 0:03:22.300 30/1(30.000) fps
auo [info]:  x264として ".\exe_files\x264_3106_x64.exe" を使用します。
auo [info]: converting YC48 -> nv12p(16bit), using SSE2 SSSE3 SSE4.1
auo [info]: x264 version: 0.164.3106M eaa68fa --chroma-format=all
auo [info]: x264 options...
 --input-depth 16 --output-depth 10 --preset ultrafast --tune animation --crf 23 --frames 6069 --input-res 1920x1080
--input-csp nv12 --fps 30/1 -o "C:\Users\yyuuk\YobanashiDeceive.264" "-"
raw [info]: 1920x1080p 0:0 @ 30/1 fps (cfr)
x264 [info]: using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2
x264 [info]: profile High 10, level 4.0, 4:2:0, 10-bit
x264 [info]: frame I:25    Avg QP:22.40  size:  6237
x264 [info]: frame P:2015  Avg QP:24.01  size:    19
x264 [info]: frame B:4029  Avg QP:25.52  size:    14
x264 [info]: consecutive B-frames:  0.4%  0.0% 99.6%
x264 [info]: mb I  I16..4: 100.0%  0.0%  0.0%
x264 [info]: mb P  I16..4:  0.0%  0.0%  0.0%  P16..4:  0.0%  0.0%  0.0%  0.0%  0.0%    skip:100.0%
x264 [info]: mb B  I16..4:  0.0%  0.0%  0.0%  B16..8:  0.0%  0.0%  0.0%  direct: 0.0%  skip:100.0%
x264 [info]: coded y,uvDC,uvAC intra: 0.0% 0.0% 0.0% inter: 0.0% 0.0% 0.0%
x264 [info]: i16 v,h,dc,p: 99%  0%  1%  0%
x264 [info]: i8c dc,h,v,p: 100%  0%  0%  0%
x264 [info]: kb/s:9.89

encoded 6069 frames, 16.93 fps, 9.89 kb/s
auo [info]: CPU使用率: Aviutl: 49.30% / x264: 17.72%
auo [info]: Aviutl 平均フレーム取得時間: 26.771 ms
auo [info]: x264エンコード時間 : 0時間 5分58.5秒
auo [info]: 総エンコード時間   : 0時間 5分59.4秒

**Comment by resistorsytrus** [comment]
正式なx264(同じver)をコマンドラインから呼び出すと10ビットでも正常に行えているので、原因がわかりません。

**Comment by rigaya** [comment]
ログのご提供ありがとうございます。

ログのおかげで、原因がAVX2が使用できない環境での処理にあることがわかりました。[x264guiEx 3.25](https://github.com/rigaya/x264guiEx/releases/tag/3.25)で修正できていると思います。

**Comment by resistorsytrus** [comment]
ありがとうございます!
